service: django-email-service

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline

custom:
  wsgi:
    app: email_service.wsgi.application
    packRequirements: false

functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  serverless-offline:
    port: 3000
